---

#
# set up a jenkins worker -- muy bueno!
#

- hosts:
  - "*-win*"

  roles:
    - bootstrap
    - package-upgrade
    - visual-studio
    - baselayout-windows
    - jenkins-worker-windows

  pre_tasks:
    - name: check if secret is properly set
      fail:
      failed_when: not secret
    - name: check if the Visual Studio version to install is properly set
      when: os|startswith("win")
      fail:
      failed_when: not vs

  post_tasks:
    - name: reboot Windows machines
      when: os|startswith("win")
      win_reboot:

  environment: '{{remote_env}}'
